### 機能

In [2]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [3]:
c = a.reshape(2,-1)
c

array([[1, 2],
       [3, 4]])

In [5]:
v = np.array([1,2,3,6,7,9,4,3,5]).reshape(3,-1)
v

array([[1, 2, 3],
       [6, 7, 9],
       [4, 3, 5]])

In [7]:
print(np.max(v,axis=0))
print(np.max(v,axis=1))

[6 7 9]
[3 9 5]


In [15]:
print(v[0,2])
print(v[[1,2],0])

3
[6 4]


In [16]:
v

array([[1, 2, 3],
       [6, 7, 9],
       [4, 3, 5]])

In [14]:
idx=np.ix_([0,2],[1,2])
print(v[idx])


[[2 3]
 [3 5]]


In [17]:
a = np.arange(4)
a


array([0, 1, 2, 3])

In [18]:
idx = [True, False, True, True]
a[idx]

array([0, 2, 3])

In [19]:
#内積
a = np.array([0,2,4])
b = np.array([5,7,9])
np.dot(a,b)

50

In [1]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import numpy.random as random

In [2]:
series = Series([1,2,3,4,5])
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
i = Series([1,2,3,4],
          index =['a','b','c','d'])
i

a    1
b    2
c    3
d    4
dtype: int64

In [4]:
#要素
print(i.values)
#インデックス
print(i.index)

[1 2 3 4]
Index(['a', 'b', 'c', 'd'], dtype='object')


In [5]:
data = {'ID':['100','101','102','103','104'],
        'City':['Tokyo','Osaka','Kyoto','Hokkaido','Tokyo'],
        'Birth_year':[1990,1989,1992,1997,1982],
        'Name':['Hiroshi','Akiko','Yuki','Satoru','Steve']}

df = DataFrame(data)
print(df)

    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve


In [30]:
#右はインデックス、真ん中が要素（values)、上はコラム(columns)

In [6]:
df.head()

ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve

In [7]:
df_2 = DataFrame(data, index=['a','b','c','d','e'])
df_2

ID      City  Birth_year     Name
a  100     Tokyo        1990  Hiroshi
b  101     Osaka        1989    Akiko
c  102     Kyoto        1992     Yuki
d  103  Hokkaido        1997   Satoru
e  104     Tokyo        1982    Steve

In [8]:
print(df_2.index)
print(df_2.values)
print(df_2.columns)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[['100' 'Tokyo' 1990 'Hiroshi']
 ['101' 'Osaka' 1989 'Akiko']
 ['102' 'Kyoto' 1992 'Yuki']
 ['103' 'Hokkaido' 1997 'Satoru']
 ['104' 'Tokyo' 1982 'Steve']]
Index(['ID', 'City', 'Birth_year', 'Name'], dtype='object')


In [47]:
pd.set_option('display.max_columns',50)
pd.set_option('display.max_rows', 50)

In [9]:
#web上に公開されているzip形式のファイルをダウンロード
import requests, zipfile
from io import StringIO
import io

In [10]:
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip'
#データをページから取ってくる
r = requests.get(url, stream=True)
#zipファイルを読み書きできるように展開
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()


In [11]:
stu_data_math = pd.read_csv('student-mat.csv', sep =';')
stu_data_math.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [65]:
#pd.read_csv(ファイル名)でDataFrame形式で、読み込まれる
#pd.read_csv(ファイル名, sep=';')で区切りを：から；にできる

In [12]:
stu_data_math.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64 
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64 
 7   Fedu        395 non-null    int64 
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64 
 13  studytime   395 non-null    int64 
 14  failures    395 non-null    int64 
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher    

In [13]:
stu_data_math.describe()

age        Medu        Fedu  traveltime   studytime    failures  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean    16.696203    2.749367    2.521519    1.448101    2.035443    0.334177   
std      1.276043    1.094735    1.088201    0.697505    0.839240    0.743651   
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000   
25%     16.000000    2.000000    2.000000    1.000000    1.000000    0.000000   
50%     17.000000    3.000000    2.000000    1.000000    2.000000    0.000000   
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000   
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000   

           famrel    freetime       goout        Dalc        Walc      health  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean     3.944304    3.235443    3.108861    1.481013    2.291139    3.554430   
std      0.896659    0.998862    1.113278    0.890741    1.287897    1.390303   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      4.000000    3.000000    2.000000    1.000000    1.000000    3.000000   
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000   
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000   
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

         absences          G1          G2          G3  
count  395.000000  395.000000  395.000000  395.000000  
mean     5.708861   10.908861   10.713924   10.415190  
std      8.003096    3.319195    3.761505    4.581443  
min      0.000000    3.000000    0.000000    0.000000  
25%      0.000000    8.000000    9.000000    8.000000  
50%      4.000000   11.000000   11.000000   11.000000  
75%      8.000000   13.000000   13.000000   14.000000  
max     75.000000   19.000000   19.000000   20.000000

In [14]:
df

ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve

In [15]:
print(df['Birth_year'])
print(df.Birth_year)
#どっちでもいい

0    1990
1    1989
2    1992
3    1997
4    1982
Name: Birth_year, dtype: int64
0    1990
1    1989
2    1992
3    1997
4    1982
Name: Birth_year, dtype: int64


In [73]:
print(df[['City','Birth_year']])

       City  Birth_year
0     Tokyo        1990
1     Osaka        1989
2     Kyoto        1992
3  Hokkaido        1997
4     Tokyo        1982


In [75]:
df

ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve

In [77]:
df['Score']=np.arange(5)*10
df

ID      City  Birth_year     Name  Score
0  100     Tokyo        1990  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [79]:
df[0:3]

ID   City  Birth_year     Name  Score
0  100  Tokyo        1990  Hiroshi      0
1  101  Osaka        1989    Akiko     10
2  102  Kyoto        1992     Yuki     20

In [80]:
df.T['ID':'Name']

0      1      2         3      4
ID              100    101    102       103    104
City          Tokyo  Osaka  Kyoto  Hokkaido  Tokyo
Birth_year     1990   1989   1992      1997   1982
Name        Hiroshi  Akiko   Yuki    Satoru  Steve

In [85]:
#行名の指定
print(df.loc[0])
print(df.loc[0:2])

ID                100
City            Tokyo
Birth_year       1990
Name          Hiroshi
Score               0
Name: 0, dtype: object
    ID   City  Birth_year     Name  Score
0  100  Tokyo        1990  Hiroshi      0
1  101  Osaka        1989    Akiko     10
2  102  Kyoto        1992     Yuki     20


In [88]:
print(df.loc[:,'City'])

0       Tokyo
1       Osaka
2       Kyoto
3    Hokkaido
4       Tokyo
Name: City, dtype: object


In [89]:
df.loc[:,['Birth_year','Name']]

Birth_year     Name
0        1990  Hiroshi
1        1989    Akiko
2        1992     Yuki
3        1997   Satoru
4        1982    Steve

In [90]:
df.loc[1,['Birth_year','Score']]

Birth_year    1989
Score           10
Name: 1, dtype: object

In [91]:
df

ID      City  Birth_year     Name  Score
0  100     Tokyo        1990  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [97]:
print(df.iloc[0:4,[0,2]])
print(df.iloc[0:2,2:4])
print(df.iloc[0,2])

    ID  Birth_year
0  100        1990
1  101        1989
2  102        1992
3  103        1997
   Birth_year     Name
0        1990  Hiroshi
1        1989    Akiko
1990


In [98]:
print(df.at[0,'ID'])

100


In [99]:
print(df.iat[0,2])

1990


In [100]:
df.at[0,'Birth_year']=2000
df

ID      City  Birth_year     Name  Score
0  100     Tokyo        2000  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [15]:
import numpy as np
import numpy.random as random
import pandas as pd
from pandas import Series, DataFrame

In [16]:
series = Series([1,1,2,3,5,8,13])
print(series)

0     1
1     1
2     2
3     3
4     5
5     8
6    13
dtype: int64


In [17]:
series_i = Series(
    [1,1,2,3,5,8,13],
    index=['a', 'b', 'c', 'd', 'e', 'f','g'])
series_i

a     1
b     1
c     2
d     3
e     5
f     8
g    13
dtype: int64

In [26]:
print(series_i.index)
print(series_i.values)

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')
[ 1  1  2  3  5  8 13]


In [27]:
import requests, zipfile
from io import StringIO
import io

In [28]:
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip'

r = requests.get(url , stream=True)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

In [32]:
#tudent_data_math = pd.read_csv('ファイル名')
student_data_math = pd.read_csv('student-mat.csv',sep = ';')
student_data_math.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [28]:
data = {'ID':['100','101','102','103','104'],
            'City':['Tokyo','Osaka','Kyoto','Hokkaido','Tokyo'],
            'Birth_year':[1990,1989,1992,1997,1982],
            'Name':['Hiroshi','Akiko','Yuki','Satoru','Steve']}

df = DataFrame(data)

print(df)

    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve


In [39]:
print(df[['City','Name']])
print(df[['ID','Birth_year']])

       City     Name
0     Tokyo  Hiroshi
1     Osaka    Akiko
2     Kyoto     Yuki
3  Hokkaido   Satoru
4     Tokyo    Steve
    ID  Birth_year
0  100        1990
1  101        1989
2  102        1992
3  103        1997
4  104        1982


In [47]:
print(df.loc[1:3,['Name','ID']])
print(df.iloc[1:3,[2,3]])

     Name   ID
1   Akiko  101
2    Yuki  102
3  Satoru  103
   Birth_year   Name
1        1989  Akiko
2        1992   Yuki


In [48]:
df['Score']=np.arange(5)*10
df

ID      City  Birth_year     Name  Score
0  100     Tokyo        1990  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [50]:
df[1:2]

ID   City  Birth_year   Name  Score
1  101  Osaka        1989  Akiko     10

In [55]:
df.loc[0:2,['Name']]

Name
0  Hiroshi
1    Akiko
2     Yuki

In [56]:
df.at[1,'ID']

'101'

In [57]:
df.iat[0,3]

'Hiroshi'

In [58]:
df.at[0,'Birth_year']=2000
df

ID      City  Birth_year     Name  Score
0  100     Tokyo        2000  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [25]:
#条件
df[df['Name']=='Akiko']

ID   City  Birth_year   Name
1  101  Tokyo        1989  Akiko

In [26]:
print(df['City']=='Tokyo')

0    True
1    True
2    True
3    True
4    True
Name: City, dtype: bool


In [31]:
df['Score']=np.arange(5)*10
df

ID      City  Birth_year     Name  Score
0  100     Tokyo        1990  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [32]:
print(df['City']=='Tokyo')

0     True
1    False
2    False
3    False
4     True
Name: City, dtype: bool


In [33]:
df[(df['Birth_year'] >=1990) & (df['Birth_year']<=1995)]

ID   City  Birth_year     Name  Score
0  100  Tokyo        1990  Hiroshi      0
2  102  Kyoto        1992     Yuki     20

In [43]:
# .isin　または
df[df['City'].isin(['Tokyo','Osaka'])]

ID   City  Birth_year     Name  Score
0  100  Tokyo        1990  Hiroshi      0
1  101  Osaka        1989    Akiko     10
4  104  Tokyo        1982    Steve     40

In [61]:
df[df['Birth_year'].isin([1990,1997])]

ID      City  Birth_year     Name  Score
0  100     Tokyo        1990  Hiroshi      0
3  103  Hokkaido        1997   Satoru     30

In [62]:
#または|
df[(df['City']=='Tokyo')|(df['Name']=='Hiroshi')]

ID   City  Birth_year     Name  Score
0  100  Tokyo        1990  Hiroshi      0
4  104  Tokyo        1982    Steve     40

In [63]:
data2 = {
    'ID':['100','101','102','103','104'],
    'City':['Tokyo','Osaka','Kyoto','Hokkaido','Tokyo'],
    'Birth_year':[1990,1989,1992,1997,1982],
    'Name':['Hiroshi','Akiko','Yuki','Satoru','Steve']
}

df_i2 = DataFrame(data2, index=['e','b','a','d','c'])
df_i2

ID      City  Birth_year     Name
e  100     Tokyo        1990  Hiroshi
b  101     Osaka        1989    Akiko
a  102     Kyoto        1992     Yuki
d  103  Hokkaido        1997   Satoru
c  104     Tokyo        1982    Steve

In [65]:
#indexでソートする(並べ替え）
df_i2.sort_index()

ID      City  Birth_year     Name
a  102     Kyoto        1992     Yuki
b  101     Osaka        1989    Akiko
c  104     Tokyo        1982    Steve
d  103  Hokkaido        1997   Satoru
e  100     Tokyo        1990  Hiroshi

In [66]:
#値によるソート
df_i2.sort_values(by='Birth_year')

ID      City  Birth_year     Name
c  104     Tokyo        1982    Steve
b  101     Osaka        1989    Akiko
e  100     Tokyo        1990  Hiroshi
a  102     Kyoto        1992     Yuki
d  103  Hokkaido        1997   Satoru

In [68]:
df_i2.sort_values(by='Birth_year',ascending=False)

ID      City  Birth_year     Name
d  103  Hokkaido        1997   Satoru
a  102     Kyoto        1992     Yuki
e  100     Tokyo        1990  Hiroshi
b  101     Osaka        1989    Akiko
c  104     Tokyo        1982    Steve

In [70]:
#アルファベット
df_i2.sort_values(by='Name')

ID      City  Birth_year     Name
b  101     Osaka        1989    Akiko
e  100     Tokyo        1990  Hiroshi
d  103  Hokkaido        1997   Satoru
c  104     Tokyo        1982    Steve
a  102     Kyoto        1992     Yuki

In [72]:
#値(values)があるかどうか
df['City'].isin(['Tokyo'])

0     True
1    False
2    False
3    False
4     True
Name: City, dtype: bool

In [80]:
df_i2['Name']=np.nan
df_i2.isnull()

ID   City  Birth_year  Name
e  False  False       False  True
b  False  False       False  True
a  False  False       False  True
d  False  False       False  True
c  False  False       False  True

In [78]:
df.isin(['Osaka'])

ID   City  Birth_year   Name  Score
0  False  False       False  False  False
1  False   True       False  False  False
2  False  False       False  False  False
3  False  False       False  False  False
4  False  False       False  False  False

In [82]:
df_i2.isnull()

ID   City  Birth_year  Name
e  False  False       False  True
b  False  False       False  True
a  False  False       False  True
d  False  False       False  True
c  False  False       False  True

In [83]:
#nullを判定して、合計する
df_i2.isnull().sum()

ID            0
City          0
Birth_year    0
Name          5
dtype: int64

In [86]:
#データの結合
data1 = {
    'id': ['100', '101', '102', '103', '104', '106', '108', '110', '111',' 113'],
    'city': ['Tokyo', 'Osaka', 'Kyoto', 'Hokkaido', 'Tokyo', 'Tokyo', 'Osaka', 'Kyoto', 'Hokkaido', 'Tokyo'],
    'birth_year': [1990, 1989, 1992, 1997, 1982, 1991, 1988, 1990, 1995, 1981],
    'name': ['Hiroshi', 'Akiko', 'Yuki', 'Satoru', 'Steeve', 'Mituru', 'Aoi', 'Tarou', 'Suguru','Mitsuo']
}

df1 = DataFrame(data1)
df1

id      city  birth_year     name
0   100     Tokyo        1990  Hiroshi
1   101     Osaka        1989    Akiko
2   102     Kyoto        1992     Yuki
3   103  Hokkaido        1997   Satoru
4   104     Tokyo        1982   Steeve
5   106     Tokyo        1991   Mituru
6   108     Osaka        1988      Aoi
7   110     Kyoto        1990    Tarou
8   111  Hokkaido        1995   Suguru
9   113     Tokyo        1981   Mitsuo

In [87]:
data2 = {
    'id': ['100', '101', '102', '105', '107'],
    'math': [50, 43, 33, 76, 98],
    'english': [90, 30, 20, 50, 30],
    'sex': ['M','F','F','M','M'],
    'index_num': [0, 1, 2, 3, 4]
}
df2 = DataFrame(data2)
df2

id  math  english sex  index_num
0  100    50       90   M          0
1  101    43       30   F          1
2  102    33       20   F          2
3  105    76       50   M          3
4  107    98       30   M          4

In [ ]:
#内部結合：両方に共通するキーがあるとき結合
#左外部結合：左側にあるデータのキーがあるときに結合する
#右外部結合：右側にあるキーに合わせて結合
#完全外部結合：

In [88]:
#内部結合
pd.merge(df1,df2)

id   city  birth_year     name  math  english sex  index_num
0  100  Tokyo        1990  Hiroshi    50       90   M          0
1  101  Osaka        1989    Akiko    43       30   F          1
2  102  Kyoto        1992     Yuki    33       20   F          2

In [89]:
pd.merge(df1,df2,on= 'id')

id   city  birth_year     name  math  english sex  index_num
0  100  Tokyo        1990  Hiroshi    50       90   M          0
1  101  Osaka        1989    Akiko    43       30   F          1
2  102  Kyoto        1992     Yuki    33       20   F          2

In [90]:
df1

id      city  birth_year     name
0   100     Tokyo        1990  Hiroshi
1   101     Osaka        1989    Akiko
2   102     Kyoto        1992     Yuki
3   103  Hokkaido        1997   Satoru
4   104     Tokyo        1982   Steeve
5   106     Tokyo        1991   Mituru
6   108     Osaka        1988      Aoi
7   110     Kyoto        1990    Tarou
8   111  Hokkaido        1995   Suguru
9   113     Tokyo        1981   Mitsuo

In [91]:
df2

id  math  english sex  index_num
0  100    50       90   M          0
1  101    43       30   F          1
2  102    33       20   F          2
3  105    76       50   M          3
4  107    98       30   M          4

In [97]:
pd.merge(df1,df2,left_index=True,right_on='index_num')

id_x      city  birth_year     name id_y  math  english sex  index_num
0  100     Tokyo        1990  Hiroshi  100    50       90   M          0
1  101     Osaka        1989    Akiko  101    43       30   F          1
2  102     Kyoto        1992     Yuki  102    33       20   F          2
3  103  Hokkaido        1997   Satoru  105    76       50   M          3
4  104     Tokyo        1982   Steeve  107    98       30   M          4

In [100]:
#左のデータのインデックスと、右のindex_numのvaluesを比較して一致しているものを結合する
pd.merge(df1,df2,left_index=True,right_on='index_num')

id_x      city  birth_year     name id_y  math  english sex  index_num
0  100     Tokyo        1990  Hiroshi  100    50       90   M          0
1  101     Osaka        1989    Akiko  101    43       30   F          1
2  102     Kyoto        1992     Yuki  102    33       20   F          2
3  103  Hokkaido        1997   Satoru  105    76       50   M          3
4  104     Tokyo        1982   Steeve  107    98       30   M          4

In [101]:
pd.merge(df1,df2,left_index=True,right_on='index_num',suffixes=('_1','_2'))

id_1      city  birth_year     name id_2  math  english sex  index_num
0  100     Tokyo        1990  Hiroshi  100    50       90   M          0
1  101     Osaka        1989    Akiko  101    43       30   F          1
2  102     Kyoto        1992     Yuki  102    33       20   F          2
3  103  Hokkaido        1997   Satoru  105    76       50   M          3
4  104     Tokyo        1982   Steeve  107    98       30   M          4

In [102]:
df1

id      city  birth_year     name
0   100     Tokyo        1990  Hiroshi
1   101     Osaka        1989    Akiko
2   102     Kyoto        1992     Yuki
3   103  Hokkaido        1997   Satoru
4   104     Tokyo        1982   Steeve
5   106     Tokyo        1991   Mituru
6   108     Osaka        1988      Aoi
7   110     Kyoto        1990    Tarou
8   111  Hokkaido        1995   Suguru
9   113     Tokyo        1981   Mitsuo

In [103]:
df2

id  math  english sex  index_num
0  100    50       90   M          0
1  101    43       30   F          1
2  102    33       20   F          2
3  105    76       50   M          3
4  107    98       30   M          4

In [104]:
pd.merge(df1,df2,how='left')

id      city  birth_year     name  math  english  sex  index_num
0   100     Tokyo        1990  Hiroshi  50.0     90.0    M        0.0
1   101     Osaka        1989    Akiko  43.0     30.0    F        1.0
2   102     Kyoto        1992     Yuki  33.0     20.0    F        2.0
3   103  Hokkaido        1997   Satoru   NaN      NaN  NaN        NaN
4   104     Tokyo        1982   Steeve   NaN      NaN  NaN        NaN
5   106     Tokyo        1991   Mituru   NaN      NaN  NaN        NaN
6   108     Osaka        1988      Aoi   NaN      NaN  NaN        NaN
7   110     Kyoto        1990    Tarou   NaN      NaN  NaN        NaN
8   111  Hokkaido        1995   Suguru   NaN      NaN  NaN        NaN
9   113     Tokyo        1981   Mitsuo   NaN      NaN  NaN        NaN

In [106]:
pd.merge(df1,df2,how='right')

id   city  birth_year     name  math  english sex  index_num
0  100  Tokyo      1990.0  Hiroshi    50       90   M          0
1  101  Osaka      1989.0    Akiko    43       30   F          1
2  102  Kyoto      1992.0     Yuki    33       20   F          2
3  105    NaN         NaN      NaN    76       50   M          3
4  107    NaN         NaN      NaN    98       30   M          4

In [107]:
pd.merge(df1,df2,how='outer')

id      city  birth_year     name  math  english  sex  index_num
0    113     Tokyo      1981.0   Mitsuo   NaN      NaN  NaN        NaN
1    100     Tokyo      1990.0  Hiroshi  50.0     90.0    M        0.0
2    101     Osaka      1989.0    Akiko  43.0     30.0    F        1.0
3    102     Kyoto      1992.0     Yuki  33.0     20.0    F        2.0
4    103  Hokkaido      1997.0   Satoru   NaN      NaN  NaN        NaN
5    104     Tokyo      1982.0   Steeve   NaN      NaN  NaN        NaN
6    105       NaN         NaN      NaN  76.0     50.0    M        3.0
7    106     Tokyo      1991.0   Mituru   NaN      NaN  NaN        NaN
8    107       NaN         NaN      NaN  98.0     30.0    M        4.0
9    108     Osaka      1988.0      Aoi   NaN      NaN  NaN        NaN
10   110     Kyoto      1990.0    Tarou   NaN      NaN  NaN        NaN
11   111  Hokkaido      1995.0   Suguru   NaN      NaN  NaN        NaN

In [108]:
data3 = {
    'id': ['117', '118', '119', '120', '125'],
    'city': ['Chiba', 'Kanagawa', 'Tokyo', 'Fukuoka', 'Okinawa'],
    'birth_year': [1990, 1989, 1992, 1997, 1982],
    'name': ['Suguru', 'Kouichi', 'Satochi', 'Yukie', 'Akari']
}
df3 = DataFrame(data3)
df3

id      city  birth_year     name
0  117     Chiba        1990   Suguru
1  118  Kanagawa        1989  Kouichi
2  119     Tokyo        1992  Satochi
3  120   Fukuoka        1997    Yukie
4  125   Okinawa        1982    Akari

In [109]:
df1

id      city  birth_year     name
0   100     Tokyo        1990  Hiroshi
1   101     Osaka        1989    Akiko
2   102     Kyoto        1992     Yuki
3   103  Hokkaido        1997   Satoru
4   104     Tokyo        1982   Steeve
5   106     Tokyo        1991   Mituru
6   108     Osaka        1988      Aoi
7   110     Kyoto        1990    Tarou
8   111  Hokkaido        1995   Suguru
9   113     Tokyo        1981   Mitsuo

In [110]:
pd.concat([df1,df3])

id      city  birth_year     name
0   100     Tokyo        1990  Hiroshi
1   101     Osaka        1989    Akiko
2   102     Kyoto        1992     Yuki
3   103  Hokkaido        1997   Satoru
4   104     Tokyo        1982   Steeve
5   106     Tokyo        1991   Mituru
6   108     Osaka        1988      Aoi
7   110     Kyoto        1990    Tarou
8   111  Hokkaido        1995   Suguru
9   113     Tokyo        1981   Mitsuo
0   117     Chiba        1990   Suguru
1   118  Kanagawa        1989  Kouichi
2   119     Tokyo        1992  Satochi
3   120   Fukuoka        1997    Yukie
4   125   Okinawa        1982    Akari

In [124]:
pd.concat([df1,df3],ignore_index=True)

id      city  birth_year     name
0    100     Tokyo        1990  Hiroshi
1    101     Osaka        1989    Akiko
2    102     Kyoto        1992     Yuki
3    103  Hokkaido        1997   Satoru
4    104     Tokyo        1982   Steeve
5    106     Tokyo        1991   Mituru
6    108     Osaka        1988      Aoi
7    110     Kyoto        1990    Tarou
8    111  Hokkaido        1995   Suguru
9    113     Tokyo        1981   Mitsuo
10   117     Chiba        1990   Suguru
11   118  Kanagawa        1989  Kouichi
12   119     Tokyo        1992  Satochi
13   120   Fukuoka        1997    Yukie
14   125   Okinawa        1982    Akari

In [125]:
pd.concat([df1,df2])

id      city  birth_year     name  math  english  sex  index_num
0   100     Tokyo      1990.0  Hiroshi   NaN      NaN  NaN        NaN
1   101     Osaka      1989.0    Akiko   NaN      NaN  NaN        NaN
2   102     Kyoto      1992.0     Yuki   NaN      NaN  NaN        NaN
3   103  Hokkaido      1997.0   Satoru   NaN      NaN  NaN        NaN
4   104     Tokyo      1982.0   Steeve   NaN      NaN  NaN        NaN
5   106     Tokyo      1991.0   Mituru   NaN      NaN  NaN        NaN
6   108     Osaka      1988.0      Aoi   NaN      NaN  NaN        NaN
7   110     Kyoto      1990.0    Tarou   NaN      NaN  NaN        NaN
8   111  Hokkaido      1995.0   Suguru   NaN      NaN  NaN        NaN
9   113     Tokyo      1981.0   Mitsuo   NaN      NaN  NaN        NaN
0   100       NaN         NaN      NaN  50.0     90.0    M        0.0
1   101       NaN         NaN      NaN  43.0     30.0    F        1.0
2   102       NaN         NaN      NaN  33.0     20.0    F        2.0
3   105       NaN         NaN      NaN  76.0     50.0    M        3.0
4   107       NaN         NaN      NaN  98.0     30.0    M        4.0

In [130]:
pd.concat([df1,df2],sort=True)
#カラム名を並べ替え

birth_year      city  english    id  index_num  math     name  sex
0      1990.0     Tokyo      NaN   100        NaN   NaN  Hiroshi  NaN
1      1989.0     Osaka      NaN   101        NaN   NaN    Akiko  NaN
2      1992.0     Kyoto      NaN   102        NaN   NaN     Yuki  NaN
3      1997.0  Hokkaido      NaN   103        NaN   NaN   Satoru  NaN
4      1982.0     Tokyo      NaN   104        NaN   NaN   Steeve  NaN
5      1991.0     Tokyo      NaN   106        NaN   NaN   Mituru  NaN
6      1988.0     Osaka      NaN   108        NaN   NaN      Aoi  NaN
7      1990.0     Kyoto      NaN   110        NaN   NaN    Tarou  NaN
8      1995.0  Hokkaido      NaN   111        NaN   NaN   Suguru  NaN
9      1981.0     Tokyo      NaN   113        NaN   NaN   Mitsuo  NaN
0         NaN       NaN     90.0   100        0.0  50.0      NaN    M
1         NaN       NaN     30.0   101        1.0  43.0      NaN    F
2         NaN       NaN     20.0   102        2.0  33.0      NaN    F
3         NaN       NaN     50.0   105        3.0  76.0      NaN    M
4         NaN       NaN     30.0   107        4.0  98.0      NaN    M

In [131]:
pd.concat([df1,df2],axis=1)

id      city  birth_year     name   id  math  english  sex  index_num
0   100     Tokyo        1990  Hiroshi  100  50.0     90.0    M        0.0
1   101     Osaka        1989    Akiko  101  43.0     30.0    F        1.0
2   102     Kyoto        1992     Yuki  102  33.0     20.0    F        2.0
3   103  Hokkaido        1997   Satoru  105  76.0     50.0    M        3.0
4   104     Tokyo        1982   Steeve  107  98.0     30.0    M        4.0
5   106     Tokyo        1991   Mituru  NaN   NaN      NaN  NaN        NaN
6   108     Osaka        1988      Aoi  NaN   NaN      NaN  NaN        NaN
7   110     Kyoto        1990    Tarou  NaN   NaN      NaN  NaN        NaN
8   111  Hokkaido        1995   Suguru  NaN   NaN      NaN  NaN        NaN
9   113     Tokyo        1981   Mitsuo  NaN   NaN      NaN  NaN        NaN

In [135]:
df[df['City']=='Tokyo']

ID   City  Birth_year     Name  Score
0  100  Tokyo        1990  Hiroshi      0
4  104  Tokyo        1982    Steve     40

In [136]:
df

ID      City  Birth_year     Name  Score
0  100     Tokyo        1990  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [137]:
df.drop(['Birth_year'],axis=1)

ID      City     Name  Score
0  100     Tokyo  Hiroshi      0
1  101     Osaka    Akiko     10
2  102     Kyoto     Yuki     20
3  103  Hokkaido   Satoru     30
4  104     Tokyo    Steve     40

In [138]:
data = {'ID':['100','101','102','103','104'],
            'City':['Tokyo','Osaka','Kyoto','Hokkaido','Tokyo'],
            'Birth_year':[1990,1989,1992,1997,1982],
            'Name':['Hiroshi','Akiko','Yuki','Satoru','Steve']}

df = DataFrame(data)

print(df)

    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve


In [139]:
df['Score']=np.arange(5)*10

In [140]:
df

ID      City  Birth_year     Name  Score
0  100     Tokyo        1990  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [142]:
df.drop(['Birth_year'],axis=1)

ID      City     Name  Score
0  100     Tokyo  Hiroshi      0
1  101     Osaka    Akiko     10
2  102     Kyoto     Yuki     20
3  103  Hokkaido   Satoru     30
4  104     Tokyo    Steve     40

In [144]:
#.reset_index()でインデックスを連続に、
df.drop(index=[0,2]).reset_index()

index   ID      City  Birth_year    Name  Score
0      1  101     Osaka        1989   Akiko     10
1      3  103  Hokkaido        1997  Satoru     30
2      4  104     Tokyo        1982   Steve     40

In [169]:
hier_df = DataFrame(
    np.arange(9).reshape(3,3),
    index = [
        ['a','b','c'],
        [1,2,2]
    ],
    columns = [
        ['Osaka','Tokyo','Osaka'],
        ['Blue','Red','Red']
    ]
)

hier_df

Osaka Tokyo Osaka
     Blue   Red   Red
a 1     0     1     2
b 2     3     4     5
c 2     6     7     8

In [153]:
hier_df.index.names = ['key1','key2']
hier_df.columns.names=['city','color']
hier_df

city      Osaka Tokyo Osaka
color      Blue   Red   Red
key1 key2                  
a    1        0     1     2
b    2        3     4     5
c    2        6     7     8

In [154]:
hier_df['Osaka']

color      Blue  Red
key1 key2           
a    1        0    2
b    2        3    5
c    2        6    8

In [158]:
hier_df.groupby(level='key2' , axis=0).sum()

/var/folders/3x/8k7v_11s16vgs7lky0_9jwrm0000gn/T/ipykernel_15677/1178919761.py:1: FutureWarning: The 'axis' keyword in DataFrame.groupby is deprecated and will be removed in a future version.
  hier_df.groupby(level='key2' , axis=0).sum()


city  Osaka Tokyo Osaka
color  Blue   Red   Red
key2                   
1         0     1     2
2         9    11    13

In [162]:
hier_df.groupby(level='color',axis=1).mean()

/var/folders/3x/8k7v_11s16vgs7lky0_9jwrm0000gn/T/ipykernel_15677/1287237984.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  hier_df.groupby(level='color',axis=1).mean()


color      Blue  Red
key1 key2           
a    1      0.0  1.5
b    2      3.0  4.5
c    2      6.0  7.5

In [174]:
#変数.drop([インデックス])
hier_df.drop(labels=[1],level=1)

Osaka Tokyo Osaka
     Blue   Red   Red
b 2     3     4     5
c 2     6     7     8

In [175]:
# hier_dfを用意
hier_df= DataFrame(
    np.arange(9).reshape((3, 3)),
    index = [
        ['a', 'a', 'b'],
        [1, 2, 2]
    ],
    columns = [
        ['Osaka', 'Tokyo', 'Osaka'],
        ['Blue','Red','Red']
    ]
)
hier_df

Osaka Tokyo Osaka
     Blue   Red   Red
a 1     0     1     2
  2     3     4     5
b 2     6     7     8

In [177]:
hier_df.stack()

/var/folders/3x/8k7v_11s16vgs7lky0_9jwrm0000gn/T/ipykernel_15677/4260390342.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  hier_df.stack()


Osaka  Tokyo
a 1 Blue      0    NaN
    Red       2    1.0
  2 Blue      3    NaN
    Red       5    4.0
b 2 Blue      6    NaN
    Red       8    7.0

In [178]:
hier_df.stack().unstack()

/var/folders/3x/8k7v_11s16vgs7lky0_9jwrm0000gn/T/ipykernel_15677/843577800.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  hier_df.stack().unstack()


Osaka     Tokyo     
     Blue Red  Blue  Red
a 1     0   2   NaN  1.0
  2     3   5   NaN  4.0
b 2     6   8   NaN  7.0

In [179]:
#　重複があるデータ
dupli_data = DataFrame({
        'col1': [1, 1, 2, 3, 4, 4, 6, 6],
        'col2': ['a', 'b', 'b', 'b', 'c', 'c', 'b', 'b']
})
print('・元のデータ')
dupli_data

・元のデータ


col1 col2
0     1    a
1     1    b
2     2    b
3     3    b
4     4    c
5     4    c
6     6    b
7     6    b

In [180]:
dupli_data.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7     True
dtype: bool

In [181]:
dupli_data.drop_duplicates()

col1 col2
0     1    a
1     1    b
2     2    b
3     3    b
4     4    c
6     6    b

In [182]:
df

ID      City  Birth_year     Name  Score
0  100     Tokyo        1990  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [184]:
#マッピング処理：参照テーブルからキーに対応するデータを持ってくる
city_map ={
    'Tokyo':'Kanto',
    'Hokkaido':'Hokkaido',
    'Osaka':'Kansai',
    'Kyoto':'Kansai'
}
city_map

{'Tokyo': 'Kanto',
 'Hokkaido': 'Hokkaido',
 'Osaka': 'Kansai',
 'Kyoto': 'Kansai'}

In [188]:
df1['region']=df1['city'].map(city_map)
df1

id      city  birth_year     name    region
0   100     Tokyo        1990  Hiroshi     Kanto
1   101     Osaka        1989    Akiko    Kansai
2   102     Kyoto        1992     Yuki    Kansai
3   103  Hokkaido        1997   Satoru  Hokkaido
4   104     Tokyo        1982   Steeve     Kanto
5   106     Tokyo        1991   Mituru     Kanto
6   108     Osaka        1988      Aoi    Kansai
7   110     Kyoto        1990    Tarou    Kansai
8   111  Hokkaido        1995   Suguru  Hokkaido
9   113     Tokyo        1981   Mitsuo     Kanto

In [191]:
df1['up_two_num'] = df1['birth_year'].map(lambda x : str(x)[0:3])
df1

id      city  birth_year     name    region up_two_num
0   100     Tokyo        1990  Hiroshi     Kanto        199
1   101     Osaka        1989    Akiko    Kansai        198
2   102     Kyoto        1992     Yuki    Kansai        199
3   103  Hokkaido        1997   Satoru  Hokkaido        199
4   104     Tokyo        1982   Steeve     Kanto        198
5   106     Tokyo        1991   Mituru     Kanto        199
6   108     Osaka        1988      Aoi    Kansai        198
7   110     Kyoto        1990    Tarou    Kansai        199
8   111  Hokkaido        1995   Suguru  Hokkaido        199
9   113     Tokyo        1981   Mitsuo     Kanto        198

In [193]:
str(df['Birth_year'])[0:3]

'0  '

In [194]:
df

ID      City  Birth_year     Name  Score
0  100     Tokyo        1990  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [197]:
df['up_to_num']=df['City'].map(lambda x:str(x)[0:3])
df

ID      City  Birth_year     Name  Score up_to_num
0  100     Tokyo        1990  Hiroshi      0       Tok
1  101     Osaka        1989    Akiko     10       Osa
2  102     Kyoto        1992     Yuki     20       Kyo
3  103  Hokkaido        1997   Satoru     30       Hok
4  104     Tokyo        1982    Steve     40       Tok

In [198]:
df1

id      city  birth_year     name    region up_two_num
0   100     Tokyo        1990  Hiroshi     Kanto        199
1   101     Osaka        1989    Akiko    Kansai        198
2   102     Kyoto        1992     Yuki    Kansai        199
3   103  Hokkaido        1997   Satoru  Hokkaido        199
4   104     Tokyo        1982   Steeve     Kanto        198
5   106     Tokyo        1991   Mituru     Kanto        199
6   108     Osaka        1988      Aoi    Kansai        198
7   110     Kyoto        1990    Tarou    Kansai        199
8   111  Hokkaido        1995   Suguru  Hokkaido        199
9   113     Tokyo        1981   Mitsuo     Kanto        198

In [203]:
birth_year_bins = [1980, 1985, 1990, 1995, 2000]

birth_year_cut_data = pd.cut(df1['birth_year'], birth_year_bins)
birth_year_cut_data
#(1985, 1990]:1985より上、1990まで

0    (1985, 1990]
1    (1985, 1990]
2    (1990, 1995]
3    (1995, 2000]
4    (1980, 1985]
5    (1990, 1995]
6    (1985, 1990]
7    (1985, 1990]
8    (1990, 1995]
9    (1980, 1985]
Name: birth_year, dtype: category
Categories (4, interval[int64, right]): [(1980, 1985] < (1985, 1990] < (1990, 1995] < (1995, 2000]]

In [204]:
pd.value_counts(birth_year_cut_data)

/var/folders/3x/8k7v_11s16vgs7lky0_9jwrm0000gn/T/ipykernel_15677/1731862176.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(birth_year_cut_data)


birth_year
(1985, 1990]    4
(1990, 1995]    3
(1980, 1985]    2
(1995, 2000]    1
Name: count, dtype: int64

In [ ]:
group_names = ['ear]